# Generated by Django 2.0.5 on 2019-03-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_usertransaction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendquery', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=100)),
                ('transid', models.ForeignKey(on_delete='cascade', to='User.UserTransaction_Model')),
            ],
        ),
    ]
