# Generated by Django 2.0.5 on 2019-03-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=50)),
                ('carttype', models.CharField(max_length=50)),
                ('issuingbank', models.CharField(max_length=50)),
                ('cardnumber', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('issusedate', models.DateField()),
                ('expiredate', models.DateField()),
                ('pinnumber', models.IntegerField()),
                ('creditlimit', models.IntegerField()),
                ('uuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.UserRegister_Model')),
            ],
        ),
    ]
