# Generated by Django 2.0.5 on 2019-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190315_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaint_model',
            name='accountnumber',
            field=models.IntegerField(),
        ),
    ]
