# Generated by Django 2.0.5 on 2019-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190315_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcarttype', models.CharField(max_length=50)),
                ('tcardnumber', models.IntegerField()),
                ('tccv', models.IntegerField()),
                ('texpiredate', models.DateField()),
                ('tpinnumber', models.IntegerField()),
                ('tamount', models.IntegerField()),
                ('tdate', models.DateField()),
                ('ttime', models.TimeField()),
                ('tname', models.ForeignKey(on_delete='cascade', to='User.UserRegister_Model')),
            ],
        ),
    ]
